//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascotas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mascotas()
        {
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int IdMascotas { get; set; }
        public string Nombre { get; set; }
        public int AnoNac { get; set; }
        public string Estado { get; set; }
        public string Raza { get; set; }
        public string Vacunas { get; set; }
        public bool Castrado { get; set; }
        public string Foto { get; set; }
        public int IdRefugios { get; set; }
    
        public virtual Refugios Refugios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
